# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-06-16 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_auto_20210616_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenaggregatormodel',
            options={'verbose_name': 'Доступ к агрегатору', 'verbose_name_plural': 'Доступы к агрегатору'},
        ),
    ]
