# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-06-21 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_auto_20210616_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenaggregatormodel',
            name='pin',
        ),
    ]
